# landscape short name
landscapeName: ossf 
# Update with your membership structure
landscapeMemberClasses:
   - name: OpenSSF Member
     category: General
   - name: Associate Membership
     category: Associate
# SF Project record ID for your project
project: a092M00001Iw46JQAR # OpenSSF
# Name of category for members 
landscapeMemberCategory: OpenSSF Members
